/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Callback */
        get: operations["auth_callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Login */
        get: operations["auth_login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Logout */
        post: operations["auth_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Workspace */
        post: operations["switch_workspace_api_v1_auth_workspace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversation Runs */
        get: operations["list_conversation_runs_api_v1_conversations__conversation_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pdf Document */
        post: operations["create_pdf_document_api_v1_documents_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Document */
        post: operations["create_text_document_api_v1_documents_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available Models */
        get: operations["available_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Evidence */
        get: operations["list_run_evidence_api_v1_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_runs__run_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Quality */
        get: operations["get_run_quality_api_v1_runs__run_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_v1_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v2_assets_get"];
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_v2_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_v2_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset Content */
        get: operations["get_asset_content_api_v2_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets/{asset_id}/storyboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media Storyboard */
        get: operations["get_media_storyboard_api_v2_assets__asset_id__storyboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestions */
        get: operations["list_ingestions_api_v2_ingestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ingestions/{ingestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion */
        get: operations["get_ingestion_api_v2_ingestions__ingestion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ingestions/{ingestion_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Ingestion */
        post: operations["cancel_ingestion_api_v2_ingestions__ingestion_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ingestions/{ingestion_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingestion Events */
        get: operations["ingestion_events_api_v2_ingestions__ingestion_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ingestions/{ingestion_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Ingestion */
        post: operations["retry_ingestion_api_v2_ingestions__ingestion_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/renditions/{rendition_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rendition Content */
        get: operations["get_rendition_content_api_v2_renditions__rendition_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{run_id}/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Visualizations */
        get: operations["get_run_visualizations_api_v2_runs__run_id__visualizations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{run_id}/visualizations/{visualization_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run Visualization Csv */
        get: operations["export_run_visualization_csv_api_v2_runs__run_id__visualizations__visualization_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment */
        get: operations["get_segment_api_v2_segments__segment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/segments/{segment_id}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Table */
        get: operations["get_segment_table_api_v2_segments__segment_id__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Table */
        get: operations["get_table_api_v2_tables__table_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerBlock */
        AnswerBlock: {
            /** Citations */
            citations?: components["schemas"]["CitationRef"][];
            /** Claims */
            claims?: components["schemas"]["AnswerClaim"][];
            /**
             * Finalized
             * @default true
             */
            finalized: boolean;
            /** Id */
            id: string;
            /** Markdown */
            markdown: string;
        };
        /** AnswerClaim */
        AnswerClaim: {
            /**
             * Assessment Rationale
             * @default
             */
            assessment_rationale: string;
            /** @default legacy */
            assessment_state: components["schemas"]["AssessmentState"];
            /**
             * Checker Method
             * @default legacy
             */
            checker_method: string;
            /**
             * Checker Version
             * @default legacy
             */
            checker_version: string;
            /** Citation Labels */
            citation_labels: number[];
            /** @default supported */
            support_status: components["schemas"]["SupportStatus"];
            /** Text */
            text: string;
        };
        /** ArtifactView */
        ArtifactView: {
            /** Byte Count */
            byte_count: number;
            /** Content Hash */
            content_hash: string;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Download Url */
            download_url: string;
            /** File Name */
            file_name: string;
            /**
             * Format
             * @enum {string}
             */
            format: "markdown" | "json" | "html" | "pdf";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * AssessmentState
         * @enum {string}
         */
        AssessmentState: "legacy" | "deterministic_exact" | "heuristic_screened" | "semantic_assessed" | "unassessed";
        /** AssetAdmission */
        AssetAdmission: {
            asset: components["schemas"]["AssetView"];
            ingestion: components["schemas"]["IngestionView"];
        };
        /**
         * AssetStatus
         * @enum {string}
         */
        AssetStatus: "quarantined" | "queued" | "processing" | "ready" | "partial" | "failed" | "cancelled";
        /** AssetView */
        AssetView: {
            /** Byte Count */
            byte_count: number;
            /**
             * Cloud Media Allowed
             * @default false
             */
            cloud_media_allowed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Name */
            name: string;
            /** Page Count */
            page_count?: number | null;
            /** Sha256 */
            sha256: string;
            status: components["schemas"]["AssetStatus"];
            /** Width */
            width?: number | null;
        };
        /** AuthMeView */
        AuthMeView: {
            /** Auth Mode */
            auth_mode: string;
            /** Csrf Required */
            csrf_required: boolean;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role: string;
            /** Subject */
            subject: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** Body_create_asset_api_v2_assets_post */
        Body_create_asset_api_v2_assets_post: {
            /** File */
            file: string;
        };
        /** Body_create_pdf_document_api_v1_documents_pdf_post */
        Body_create_pdf_document_api_v1_documents_pdf_post: {
            /** File */
            file: string;
        };
        /** CitationRef */
        CitationRef: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Label */
            label: number;
        };
        /** ClaimEvidenceRelationView */
        ClaimEvidenceRelationView: {
            /**
             * Checker Method
             * @default legacy
             */
            checker_method: string;
            /**
             * Checker Version
             * @default legacy
             */
            checker_version: string;
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Claim Text */
            claim_text: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "supports" | "contradicts" | "contextualizes";
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
        };
        /** ConversationView */
        ConversationView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DateWindow */
        DateWindow: {
            /** End */
            end?: string | null;
            /** Start */
            start?: string | null;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "ready" | "partial" | "needs_ocr" | "failed";
        /** DocumentTextCreate */
        DocumentTextCreate: {
            /**
             * Mime Type
             * @default text/plain
             * @enum {string}
             */
            mime_type: "text/plain" | "text/markdown";
            /** Name */
            name: string;
            /** Text */
            text: string;
        };
        /** DocumentView */
        DocumentView: {
            /** Asset Id */
            asset_id?: string | null;
            /** Byte Count */
            byte_count: number;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lexical Ready
             * @default true
             */
            lexical_ready: boolean;
            /** Mime Type */
            mime_type: string;
            /** Name */
            name: string;
            /** Page Count */
            page_count?: number | null;
            /** Parser Version */
            parser_version?: string | null;
            /**
             * Semantic Ready
             * @default false
             */
            semantic_ready: boolean;
            /** @default ready */
            status: components["schemas"]["DocumentStatus"];
            /** Warnings */
            warnings?: string[];
        };
        /** EvidenceView */
        EvidenceView: {
            /** Asset Content Url */
            asset_content_url?: string | null;
            /** Asset Id */
            asset_id?: string | null;
            /** Asset Mime Type */
            asset_mime_type?: string | null;
            /** Asset Name */
            asset_name?: string | null;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Content Hash */
            content_hash: string;
            /** Document Version Id */
            document_version_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locator */
            locator: string;
            /** Locator Data */
            locator_data?: {
                [key: string]: unknown;
            } | null;
            /** Page End */
            page_end?: number | null;
            /** Page Start */
            page_start?: number | null;
            /** Segment Id */
            segment_id?: string | null;
            source: components["schemas"]["SourceView"];
            support_status: components["schemas"]["SupportStatus"];
            /** Text */
            text: string;
        };
        /** ExportCreate */
        ExportCreate: {
            /**
             * Format
             * @enum {string}
             */
            format: "markdown" | "json" | "html" | "pdf";
        };
        /** FrameRegionLocator */
        FrameRegionLocator: {
            /**
             * Bbox
             * @default [
             *       0,
             *       0,
             *       1,
             *       1
             *     ]
             */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Coordinate Space
             * @default normalized_top_left
             * @constant
             */
            coordinate_space: "normalized_top_left";
            /** Frame Id */
            frame_id?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "frame_region";
            /** Presentation Time Ms */
            presentation_time_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionStage
         * @enum {string}
         */
        IngestionStage: "quarantined" | "queued" | "parsing" | "enriching" | "indexing" | "ready" | "partial" | "failed" | "cancelled";
        /**
         * IngestionStatus
         * @enum {string}
         */
        IngestionStatus: "queued" | "running" | "ready" | "partial" | "failed" | "cancelled";
        /** IngestionView */
        IngestionView: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Cancellation Requested
             * @default false
             */
            cancellation_requested: boolean;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seq
             * @default 0
             */
            last_seq: number;
            /**
             * Lexical Ready
             * @default false
             */
            lexical_ready: boolean;
            /**
             * Semantic Ready
             * @default false
             */
            semantic_ready: boolean;
            stage: components["schemas"]["IngestionStage"];
            status: components["schemas"]["IngestionStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Warnings */
            warnings?: string[];
        };
        /** MediaFrameView */
        MediaFrameView: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Content Hash */
            content_hash: string;
            /** Content Url */
            content_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Extraction Version Id */
            extraction_version_id?: string | null;
            /** Height */
            height: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Presentation Time Ms */
            presentation_time_ms: number;
            /**
             * Rendition Id
             * Format: uuid
             */
            rendition_id: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "periodic" | "scene";
            /** Width */
            width: number;
        };
        /** MediaStoryboardView */
        MediaStoryboardView: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Frames */
            frames?: components["schemas"]["MediaFrameView"][];
            /** Sampled Times Ms */
            sampled_times_ms?: number[];
            /** Sampling Strategy */
            sampling_strategy: string;
            /** Tracks */
            tracks?: components["schemas"]["MediaTrackView"][];
            /** Visual Coverage Warning */
            visual_coverage_warning?: string | null;
            /** Waveform Peaks */
            waveform_peaks?: number[];
        };
        /** MediaTrackView */
        MediaTrackView: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Average Frame Rate */
            average_frame_rate?: string | null;
            /** Channels */
            channels?: number | null;
            /** Codec Name */
            codec_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Extraction Version Id */
            extraction_version_id?: string | null;
            /** Height */
            height?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Sample Rate */
            sample_rate?: number | null;
            /** Stream Index */
            stream_index: number;
            /**
             * Track Type
             * @enum {string}
             */
            track_type: "audio" | "video";
            /** Width */
            width?: number | null;
        };
        /** PageRegionLocator */
        PageRegionLocator: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Coordinate Space
             * @default normalized_top_left
             * @constant
             */
            coordinate_space: "normalized_top_left";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "page_region";
            /** Page */
            page: number;
            /**
             * Rotation Degrees
             * @default 0
             */
            rotation_degrees: number;
        };
        /** RunCreate */
        RunCreate: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            date_window?: components["schemas"]["DateWindow"] | null;
            /** Document Ids */
            document_ids?: string[];
            /** @default quick */
            mode: components["schemas"]["RunMode"];
            /** Model Provider */
            model_provider?: ("gemini" | "qwen") | null;
            /** Plugins */
            plugins?: string[];
            /** Query */
            query: string;
            /** Source Scope */
            source_scope?: ("web" | "academic" | "software" | "documents")[];
        };
        /** RunFacetView */
        RunFacetView: {
            /**
             * Checker Method
             * @default deterministic
             */
            checker_method: string;
            /**
             * Checker Version
             * @default m10-v1
             */
            checker_version: string;
            /** Conflicting Evidence Ids */
            conflicting_evidence_ids?: string[];
            /** Facet Key */
            facet_key: string;
            /**
             * Independent Origin Count
             * @default 0
             */
            independent_origin_count: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "conflicting" | "missing";
            /** Supporting Evidence Ids */
            supporting_evidence_ids?: string[];
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "quick" | "research";
        /** RunQualityView */
        RunQualityView: {
            /** Citation Resolution Rate */
            citation_resolution_rate: number;
            /** Claim Citation Rate */
            claim_citation_rate: number;
            /** Claim Count */
            claim_count: number;
            /** Confidence Extraction */
            confidence_extraction?: number | null;
            /** Confidence Relevance */
            confidence_relevance?: number | null;
            /** Confidence Support */
            confidence_support?: number | null;
            /** Distinct Source Group Count */
            distinct_source_group_count: number;
            /**
             * Duplicate Sources Removed
             * @default 0
             */
            duplicate_sources_removed: number;
            /** Evidence Count */
            evidence_count: number;
            /** Evidence Relation Counts */
            evidence_relation_counts?: {
                [key: string]: number;
            };
            /** Evidence Relations */
            evidence_relations?: components["schemas"]["ClaimEvidenceRelationView"][];
            /** Facets */
            facets?: components["schemas"]["RunFacetView"][];
            /**
             * Gaps Count
             * @default 0
             */
            gaps_count: number;
            /** Provider Counts */
            provider_counts?: {
                [key: string]: number;
            };
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /**
             * Risky Source Events
             * @default 0
             */
            risky_source_events: number;
            /** Run Elapsed Ms */
            run_elapsed_ms?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source Count */
            source_count: number;
            /** Source Kind Counts */
            source_kind_counts?: {
                [key: string]: number;
            };
            /** Stage Timings Ms */
            stage_timings_ms?: {
                [key: string]: number;
            };
            /** Support Counts */
            support_counts?: {
                [key: string]: number;
            };
            /** Supported Claim Rate */
            supported_claim_rate: number;
        };
        /** RunSnapshot */
        RunSnapshot: {
            /** Answer Blocks */
            answer_blocks?: components["schemas"]["AnswerBlock"][];
            /**
             * Budget Version
             * @default legacy
             */
            budget_version: string;
            /**
             * Cancellation Requested
             * @default false
             */
            cancellation_requested: boolean;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            date_window?: components["schemas"]["DateWindow"] | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Document Ids */
            document_ids?: string[];
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Gaps */
            gaps?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seq
             * @default 0
             */
            last_seq: number;
            mode: components["schemas"]["RunMode"];
            /** Model Provider */
            model_provider?: ("gemini" | "qwen") | null;
            /** Plugins */
            plugins?: string[];
            /** Query */
            query: string;
            /** Related Questions */
            related_questions?: string[];
            /** Source Scope */
            source_scope?: string[];
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Usage Ledger */
            usage_ledger?: {
                [key: string]: number;
            };
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "planning" | "discovering" | "reading" | "extracting" | "checking" | "synthesizing" | "completed" | "partial" | "failed" | "cancelled";
        /** SegmentView */
        SegmentView: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Confidence */
            confidence?: number | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Derivation Kind */
            derivation_kind: string;
            /** Document Id */
            document_id?: string | null;
            /**
             * Extraction Version Id
             * Format: uuid
             */
            extraction_version_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language?: string | null;
            /** Locator */
            locator: components["schemas"]["TextLocator"] | components["schemas"]["PageRegionLocator"] | components["schemas"]["TableCellsLocator"] | components["schemas"]["TimeRangeLocator"] | components["schemas"]["FrameRegionLocator"];
            /**
             * Modality
             * @enum {string}
             */
            modality: "text" | "image" | "table_cell" | "audio" | "video_frame";
            /** Origin Group Id */
            origin_group_id?: string | null;
            /** Text */
            text?: string | null;
        };
        /** SourceView */
        SourceView: {
            /** Canonical Identifier */
            canonical_identifier?: string | null;
            /** Discovery Rank */
            discovery_rank?: number | null;
            /** Domain */
            domain: string;
            /** Extraction Method */
            extraction_method: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Provider
             * @default web
             */
            provider: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Read State
             * @default full
             * @enum {string}
             */
            read_state: "full" | "snippet_only" | "blocked";
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /**
             * Source Kind
             * @default web
             * @enum {string}
             */
            source_kind: "web" | "academic" | "software" | "document";
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /**
         * SupportStatus
         * @enum {string}
         */
        SupportStatus: "supported" | "partially_supported" | "conflicting" | "insufficient_evidence";
        /** TableCellView */
        TableCellView: {
            /** Column */
            column: number;
            /**
             * Column Span
             * @default 1
             */
            column_span: number;
            /**
             * Is Header
             * @default false
             */
            is_header: boolean;
            /** Normalized Value */
            normalized_value?: string | number | null;
            /** Raw Text */
            raw_text: string;
            /** Row */
            row: number;
            /**
             * Row Span
             * @default 1
             */
            row_span: number;
            /** Segment Id */
            segment_id?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** TableCellsLocator */
        TableCellsLocator: {
            /** Columns */
            columns: number[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table_cells";
            /** Page */
            page?: number | null;
            /** Rows */
            rows: number[];
            /** Table Id */
            table_id: string;
        };
        /** TableView */
        TableView: {
            /** Cells */
            cells?: components["schemas"]["TableCellView"][];
            /** Columns */
            columns: number;
            /**
             * Extraction Version Id
             * Format: uuid
             */
            extraction_version_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locator */
            locator?: (components["schemas"]["TextLocator"] | components["schemas"]["PageRegionLocator"] | components["schemas"]["TableCellsLocator"] | components["schemas"]["TimeRangeLocator"] | components["schemas"]["FrameRegionLocator"]) | null;
            /** Page */
            page?: number | null;
            /** Rows */
            rows: number;
            /** Table Key */
            table_key: string;
        };
        /** TextLocator */
        TextLocator: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
        };
        /** TimeRangeLocator */
        TimeRangeLocator: {
            /** End Ms */
            end_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "time_range";
            /** Start Ms */
            start_ms: number;
            /**
             * Track
             * @default audio
             * @enum {string}
             */
            track: "audio" | "video";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualizationKind
         * @enum {string}
         */
        VisualizationKind: "comparison_matrix" | "bar" | "line" | "scatter" | "timeline" | "evidence_map";
        /** VisualizationLineageRef */
        VisualizationLineageRef: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Locator
             * @default
             */
            locator: string;
            /** Segment Id */
            segment_id?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** VisualizationSpec */
        VisualizationSpec: {
            /**
             * Accessible Table
             * @default true
             */
            accessible_table: boolean;
            /**
             * Allow Download Csv
             * @default true
             */
            allow_download_csv: boolean;
            kind: components["schemas"]["VisualizationKind"];
            /**
             * Max Points
             * @default 200
             */
            max_points: number;
            /**
             * Renderer
             * @default svg
             * @enum {string}
             */
            renderer: "svg" | "canvas";
            /** Series Field */
            series_field?: string | null;
            /** Unit */
            unit?: string | null;
            /** X Field */
            x_field?: string | null;
            /** Y Field */
            y_field?: string | null;
        };
        /** VisualizationView */
        VisualizationView: {
            approved_spec: components["schemas"]["VisualizationSpec"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Lineage */
            data_lineage?: components["schemas"]["VisualizationLineageRef"][];
            /** Dataset */
            dataset: {
                [key: string]: unknown;
            };
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Export Metadata */
            export_metadata?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["VisualizationKind"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Title */
            title: string;
        };
        /** WorkspaceSwitchRequest */
        WorkspaceSwitchRequest: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** WorkspaceView */
        WorkspaceView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    download_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_callback_api_v1_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_login_api_v1_auth_login_get: {
        parameters: {
            query?: {
                return_path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeView"];
                };
            };
        };
    };
    switch_workspace_api_v1_auth_workspace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"][];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversation_runs_api_v1_conversations__conversation_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"][];
                };
            };
        };
    };
    create_pdf_document_api_v1_documents_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_pdf_document_api_v1_documents_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_text_document_api_v1_documents_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentTextCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_evidence_api_v1_runs__run_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_v1_runs__run_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_quality_api_v1_runs__run_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunQualityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"][];
                };
            };
        };
    };
    list_assets_api_v2_assets_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_api_v2_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_asset_api_v2_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetAdmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v2_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_content_api_v2_assets__asset_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_storyboard_api_v2_assets__asset_id__storyboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaStoryboardView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_api_v2_ingestions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_api_v2_ingestions__ingestion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_ingestion_api_v2_ingestions__ingestion_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingestion_events_api_v2_ingestions__ingestion_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_ingestion_api_v2_ingestions__ingestion_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rendition_content_api_v2_renditions__rendition_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rendition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_visualizations_api_v2_runs__run_id__visualizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_visualization_csv_api_v2_runs__run_id__visualizations__visualization_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                visualization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lineage-bearing CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_api_v2_segments__segment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_table_api_v2_segments__segment_id__table_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table_api_v2_tables__table_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
