/* eslint-disable */
// AUTO-GENERATED by scripts/generate_frontend_types.py from backend/openapi.json.
// Do not edit by hand; run `pnpm --filter @ares/web openapi:generate`.

export interface components {
  schemas: {
    "AnswerBlock": { "citations"?: Array<components["schemas"]["CitationRef"]>; "claims"?: Array<components["schemas"]["AnswerClaim"]>; "finalized"?: boolean; "id": string; "markdown": string; };
    "AnswerClaim": { "assessment_rationale"?: string; "assessment_state"?: components["schemas"]["AssessmentState"]; "checker_method"?: string; "checker_version"?: string; "citation_labels": Array<number>; "support_status"?: components["schemas"]["SupportStatus"]; "text": string; };
    "ArtifactView": { "byte_count": number; "content_hash": string; "content_type": string; "created_at": string; "download_url": string; "file_name": string; "format": "markdown" | "json"; "id": string; "run_id": string; };
    "AssessmentState": "legacy" | "deterministic_exact" | "heuristic_screened" | "semantic_assessed" | "unassessed";
    "AssetAdmission": { "asset": components["schemas"]["AssetView"]; "ingestion": components["schemas"]["IngestionView"]; };
    "AssetStatus": "quarantined" | "queued" | "processing" | "ready" | "partial" | "failed" | "cancelled";
    "AssetView": { "byte_count": number; "cloud_media_allowed"?: boolean; "created_at": string; "duration_ms"?: number | null; "height"?: number | null; "id": string; "mime_type": string; "name": string; "page_count"?: number | null; "sha256": string; "status": components["schemas"]["AssetStatus"]; "width"?: number | null; };
    "AuthMeView": { "auth_mode": string; "csrf_required": boolean; "display_name"?: string | null; "email"?: string | null; "role": string; "subject": string; "user_id": string; "workspace_id": string; };
    "Body_create_asset_api_v2_assets_post": { "file": string; };
    "Body_create_pdf_document_api_v1_documents_pdf_post": { "file": string; };
    "CitationRef": { "evidence_id": string; "label": number; };
    "ClaimEvidenceRelationView": { "checker_method"?: string; "checker_version"?: string; "claim_id": string; "claim_text": string; "evidence_id": string; "rationale"?: string; "relation": "supports" | "contradicts" | "contextualizes"; };
    "ConversationCreate": { "title"?: string | null; };
    "ConversationView": { "created_at": string; "id": string; "title": string; "updated_at": string; };
    "DateWindow": { "end"?: string | null; "start"?: string | null; "timezone"?: string; };
    "DocumentStatus": "ready" | "partial" | "needs_ocr" | "failed";
    "DocumentTextCreate": { "mime_type"?: "text/plain" | "text/markdown"; "name": string; "text": string; };
    "DocumentView": { "asset_id"?: string | null; "byte_count": number; "content_hash": string; "created_at": string; "id": string; "lexical_ready"?: boolean; "mime_type": string; "name": string; "page_count"?: number | null; "parser_version"?: string | null; "semantic_ready"?: boolean; "status"?: components["schemas"]["DocumentStatus"]; "warnings"?: Array<string>; };
    "EvidenceView": { "asset_content_url"?: string | null; "asset_id"?: string | null; "asset_mime_type"?: string | null; "asset_name"?: string | null; "captured_at": string; "char_end"?: number | null; "char_start"?: number | null; "content_hash": string; "document_version_id"?: string | null; "id": string; "locator": string; "locator_data"?: { [key: string]: unknown; } | null; "page_end"?: number | null; "page_start"?: number | null; "segment_id"?: string | null; "source": components["schemas"]["SourceView"]; "support_status": components["schemas"]["SupportStatus"]; "text": string; };
    "ExportCreate": { "format": "markdown" | "json"; };
    "FrameRegionLocator": { "bbox"?: Array<unknown>; "coordinate_space"?: string; "frame_id"?: string | null; "kind"?: string; "presentation_time_ms": number; };
    "HTTPValidationError": { "detail"?: Array<components["schemas"]["ValidationError"]>; };
    "IngestionStage": "quarantined" | "queued" | "parsing" | "enriching" | "indexing" | "ready" | "partial" | "failed" | "cancelled";
    "IngestionStatus": "queued" | "running" | "ready" | "partial" | "failed" | "cancelled";
    "IngestionView": { "asset_id": string; "cancellation_requested"?: boolean; "completed_at"?: string | null; "created_at": string; "document_id"?: string | null; "error_code"?: string | null; "error_message"?: string | null; "id": string; "last_seq"?: number; "lexical_ready"?: boolean; "semantic_ready"?: boolean; "stage": components["schemas"]["IngestionStage"]; "status": components["schemas"]["IngestionStatus"]; "updated_at": string; "warnings"?: Array<string>; };
    "MediaFrameView": { "asset_id": string; "content_hash": string; "content_url": string; "created_at": string; "extraction_version_id"?: string | null; "height": number; "id": string; "presentation_time_ms": number; "rendition_id": string; "source_kind": "periodic" | "scene"; "width": number; };
    "MediaStoryboardView": { "asset_id": string; "duration_ms"?: number | null; "frames"?: Array<components["schemas"]["MediaFrameView"]>; "sampled_times_ms"?: Array<number>; "sampling_strategy": string; "tracks"?: Array<components["schemas"]["MediaTrackView"]>; "visual_coverage_warning"?: string | null; "waveform_peaks"?: Array<number>; };
    "MediaTrackView": { "asset_id": string; "average_frame_rate"?: string | null; "channels"?: number | null; "codec_name"?: string | null; "created_at": string; "duration_ms"?: number | null; "extraction_version_id"?: string | null; "height"?: number | null; "id": string; "language"?: string | null; "metadata"?: { [key: string]: unknown; }; "sample_rate"?: number | null; "stream_index": number; "track_type": "audio" | "video"; "width"?: number | null; };
    "PageRegionLocator": { "bbox": Array<unknown>; "coordinate_space"?: string; "kind"?: string; "page": number; "rotation_degrees"?: number; };
    "RunCreate": { "conversation_id": string; "date_window"?: components["schemas"]["DateWindow"] | null; "document_ids"?: Array<string>; "mode"?: components["schemas"]["RunMode"]; "query": string; "source_scope"?: Array<"web" | "academic" | "software" | "documents">; };
    "RunFacetView": { "checker_method"?: string; "checker_version"?: string; "conflicting_evidence_ids"?: Array<string>; "facet_key": string; "independent_origin_count"?: number; "rationale"?: string; "status": "supported" | "conflicting" | "missing"; "supporting_evidence_ids"?: Array<string>; };
    "RunMode": "quick" | "research";
    "RunQualityView": { "citation_resolution_rate": number; "claim_citation_rate": number; "claim_count": number; "distinct_source_group_count": number; "duplicate_sources_removed"?: number; "evidence_count": number; "evidence_relation_counts"?: { [key: string]: number; }; "evidence_relations"?: Array<components["schemas"]["ClaimEvidenceRelationView"]>; "facets"?: Array<components["schemas"]["RunFacetView"]>; "gaps_count"?: number; "provider_counts"?: { [key: string]: number; }; "queue_wait_ms"?: number | null; "risky_source_events"?: number; "run_elapsed_ms"?: number | null; "run_id": string; "source_count": number; "source_kind_counts"?: { [key: string]: number; }; "stage_timings_ms"?: { [key: string]: number; }; "support_counts"?: { [key: string]: number; }; "supported_claim_rate": number; };
    "RunSnapshot": { "answer_blocks"?: Array<components["schemas"]["AnswerBlock"]>; "budget_version"?: string; "cancellation_requested"?: boolean; "conversation_id": string; "created_at": string; "date_window"?: components["schemas"]["DateWindow"] | null; "deadline_at"?: string | null; "document_ids"?: Array<string>; "error_code"?: string | null; "error_message"?: string | null; "gaps"?: Array<string>; "id": string; "last_seq"?: number; "mode": components["schemas"]["RunMode"]; "query": string; "source_scope"?: Array<string>; "status": components["schemas"]["RunStatus"]; "updated_at": string; "usage_ledger"?: { [key: string]: number; }; };
    "RunStatus": "queued" | "planning" | "discovering" | "reading" | "extracting" | "checking" | "synthesizing" | "completed" | "partial" | "failed" | "cancelled";
    "SegmentView": { "asset_id": string; "confidence"?: number | null; "content_hash": string; "created_at": string; "derivation_kind": string; "document_id"?: string | null; "extraction_version_id": string; "id": string; "language"?: string | null; "locator": unknown; "modality": "text" | "image" | "table_cell" | "audio" | "video_frame"; "origin_group_id"?: string | null; "text"?: string | null; };
    "SourceView": { "canonical_identifier"?: string | null; "discovery_rank"?: number | null; "domain": string; "extraction_method": string; "fetched_at": string; "id": string; "provider"?: string; "published_at"?: string | null; "read_state"?: "full" | "snippet_only" | "blocked"; "snippet"?: string; "source_kind"?: "web" | "academic" | "software" | "document"; "title": string; "url": string; };
    "SupportStatus": "supported" | "partially_supported" | "conflicting" | "insufficient_evidence";
    "TableCellView": { "column": number; "column_span"?: number; "is_header"?: boolean; "normalized_value"?: string | number | null; "raw_text": string; "row": number; "row_span"?: number; "segment_id"?: string | null; "unit"?: string | null; };
    "TableCellsLocator": { "columns": Array<number>; "kind"?: string; "page"?: number | null; "rows": Array<number>; "table_id": string; };
    "TableView": { "cells"?: Array<components["schemas"]["TableCellView"]>; "columns": number; "extraction_version_id": string; "id": string; "locator"?: unknown | null; "page"?: number | null; "rows": number; "table_key": string; };
    "TextLocator": { "char_end": number; "char_start": number; "kind"?: string; };
    "TimeRangeLocator": { "end_ms": number; "kind"?: string; "start_ms": number; "track"?: "audio" | "video"; };
    "ValidationError": { "ctx"?: Record<string, unknown>; "input"?: unknown; "loc": Array<string | number>; "msg": string; "type": string; };
    "VisualizationKind": "comparison_matrix" | "bar" | "line" | "scatter" | "timeline" | "evidence_map";
    "VisualizationLineageRef": { "evidence_id": string; "locator"?: string; "segment_id"?: string | null; "source_id": string; };
    "VisualizationSpec": { "accessible_table"?: boolean; "allow_download_csv"?: boolean; "kind": components["schemas"]["VisualizationKind"]; "max_points"?: number; "renderer"?: "svg" | "canvas"; "series_field"?: string | null; "unit"?: string | null; "x_field"?: string | null; "y_field"?: string | null; };
    "VisualizationView": { "approved_spec": components["schemas"]["VisualizationSpec"]; "created_at": string; "data_lineage"?: Array<components["schemas"]["VisualizationLineageRef"]>; "dataset": { [key: string]: unknown; }; "dataset_id": string; "description"?: string; "export_metadata"?: { [key: string]: unknown; }; "id": string; "kind": components["schemas"]["VisualizationKind"]; "run_id": string; "schema_version"?: number; "title": string; };
    "WorkspaceSwitchRequest": { "workspace_id": string; };
    "WorkspaceView": { "id": string; "name": string; "role": string; };
  };
}
