from __future__ import annotations

from pathlib import Path
from typing import Protocol


class BlobStore(Protocol):
    def put_bytes(self, namespace: str, content: bytes) -> str: ...
    def put_file(self, namespace: str, path: str | Path) -> str: ...
    def get_bytes(self, key: str) -> bytes: ...
    def get_size(self, key: str) -> int: ...
    def get_range(self, key: str, start: int, end_inclusive: int) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
