from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "backend" / "openapi.json"
OUTPUT = ROOT / "apps" / "web" / "src" / "lib" / "api" / "generated.ts"


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return f'components["schemas"]["{name}"]'
    if "anyOf" in schema:
        values: list[str] = []
        for item in schema["anyOf"]:
            value = ts_type(item)
            if value not in values:
                values.append(value)
        return " | ".join(values) if values else "unknown"
    if "enum" in schema:
        return " | ".join("null" if value is None else json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "string": return "string"
    if kind in {"integer", "number"}: return "number"
    if kind == "boolean": return "boolean"
    if kind == "null": return "null"
    if kind == "array": return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        required = set(schema.get("required") or [])
        parts = [
            f"{json.dumps(key)}{'' if key in required else '?'}: {ts_type(value)};"
            for key, value in (schema.get("properties") or {}).items()
        ]
        additional = schema.get("additionalProperties")
        if additional is True: parts.append("[key: string]: unknown;")
        elif isinstance(additional, dict): parts.append(f"[key: string]: {ts_type(additional)};")
        return "{ " + " ".join(parts) + " }" if parts else "Record<string, unknown>"
    return "unknown"


def main() -> None:
    spec = json.loads(OPENAPI.read_text(encoding="utf-8"))
    schemas = spec.get("components", {}).get("schemas", {})
    if not schemas:
        raise SystemExit("OpenAPI components.schemas is empty")
    lines = [
        "/* eslint-disable */",
        "// AUTO-GENERATED by scripts/generate_frontend_types.py from backend/openapi.json.",
        "// Do not edit by hand; run `pnpm --filter @ares/web openapi:generate`.", "",
        "export interface components {", "  schemas: {",
    ]
    for name in sorted(schemas):
        lines.append(f"    {json.dumps(name)}: {ts_type(schemas[name])};")
    lines.extend(["  };", "}", ""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
