name: dependency-review

on:
  pull_request:

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Reject newly introduced vulnerable dependencies
        uses: actions/dependency-review-action@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fail-on-severity: high
          fail-on-scopes: development, runtime
